---
title: "Surveillance Fièvres et Paludisme dans le réseau sentinelle"
author: "Institut Pasteur de Madagascar"
date: "`r Sys.Date()`"
output: pdf_document
---



```{r,echo=F, fig.width=10, out.extra='',comment='', message=FALSE , warning=FALSE}
setwd("/media/herimanitra/DONNEES/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel")
#load source code:
source("./import_data.R");source("./tdrplus.R");require(ggplot2); require(gridExtra)
source("./var_conversion.R")
mydata= tdr_malaria(htc=F)

source("./reporting_plot.R",local = T)
generate_plot(htc="all",
              mydata=mydata,
              add_trend=T,
              legend.disease1="Paludisme TDR+",
              legend.disease2="Fièvres",
              disease1.targetvar="malaria_cases",
              disease2.targetvar="SyndF",
              title.label="Fièvres et Paludisme dans le réseau sentinelle",
              title.label.list="Fièvres et Paludisme à",
              title.ylab="Cas de Fièvres et Paludisme")
```


```{r,echo=F,out.extra='',comment='', message=FALSE , warning=FALSE}
setwd("/media/herimanitra/DONNEES/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel")
mydata= tdr_malaria(htc=F)
semaine=array()
max_deb_sem=max(as.Date(mydata$deb_sem))
semaine[6]= max_deb_sem-2*7 
p=1
for ( k in 2:6 )
{
  semaine[p]=semaine[6]-(k-1)*7
  p=p+1
}
#select last 07 seven weeks for each disease:

#Malaria selection for last 6 weeks before current week:
malaria=unique(mydata[as.Date(deb_sem) %in% semaine,list(deb_sem,sites,malaria_cases)],by=NULL)

# reverse time order (to be conform to the report)
setorder(malaria,sites,deb_sem)

#transform NA
malaria$malaria_cases=as.character(malaria$malaria_cases)
malaria[is.na(malaria_cases)==T,malaria_cases:="na"]
malaria[,malaria_cases:=ifelse(nchar(malaria_cases)<2,paste0("0",malaria_cases),
                               malaria_cases)]
#looking for missing sites for each semaine:


#get unique sites for max
liste_sites= unique(malaria$sites)
for ( s in unique(malaria$deb_sem) ) #foreach unique semaine
{ 
   #if not all sites in the current week in the total liste
    currentsiteweek= malaria[as.Date(deb_sem) == as.Date(s),get('sites')]
    if (  all (liste_sites %in% currentsiteweek   )==F )
    {
      missing_site=liste_sites[which(!(liste_sites %in%  currentsiteweek))]
    for ( p in missing_site)
      {
      #cat(p," is missing for semaine (malaria):",as.Date(s),"\n")
      tmp1 = data.table(deb_sem=as.Date(s),sites=p,malaria_cases="na")
      var_conv(malaria,tmp1)
      malaria=rbind(malaria,tmp1)
      rm(tmp1)
      }
    }
}
setorder(malaria,deb_sem,sites)

#keep unique obs.

#inline historical occurence:
malaria[,vals:=paste(malaria_cases,collapse = "-"),by="sites"]
#append latest week per site:
malaria[,malaria_cases:=NULL]

lastweek = unique(mydata[as.Date(deb_sem)==max_deb_sem-7,list(sites,malaria_cases)],by=NULL)
lastweek[,malaria_cases:=as.character(malaria_cases)]
lastweek[is.na(malaria_cases)==T,malaria_cases:="na"]
malaria= merge(unique(malaria[,list(sites,vals)],by=NULL),lastweek, 
               by.x="sites", by.y="sites")
#merge with sentinel_latlong to display name
malaria=merge(malaria,sentinel_latlong[,list(sites,name)],
             by.x="sites",by.y="sites")
#
setnames(malaria,c("name","vals","malaria_cases"),
                 c("Sites","6 semaines précédentes","Semaine dernière"))

##################################################################################

#Fiever selection for last 6 weeks before current week:
fievre=mydata[as.Date(deb_sem) %in% semaine,list(deb_sem,sites,SyndF)]
fievre=fievre[,SyndF:=sum(SyndF,na.rm = T),by="deb_sem,sites"]
fievre=unique(fievre,by=NULL)
#transform NA into XX
fievre$SyndF=as.character(fievre$SyndF)
fievre[is.na(SyndF)==T,SyndF:="na"]
fievre[,SyndF:=ifelse(nchar(SyndF)<2,paste0("0",SyndF),SyndF)]
#looking for missing sites for each semaine:

#get unique sites for max
liste_sites= unique(fievre$sites)
for ( s in unique(fievre$deb_sem) ) #foreach unique semaine
{ 
  currentsiteweek= fievre[as.Date(deb_sem) == as.Date(s),get('sites')]
    if (  all ( liste_sites %in% currentsiteweek   )==F )
    {
      missing_site=liste_sites[which(!(liste_sites %in%  currentsiteweek))]
    for ( p in missing_site)
      {
      #cat(p," is missing for semaine(fiever):",s,"\n")
      tmp1 = data.table(deb_sem=as.Date(s),sites=p,SyndF="na")
      var_conv(fievre,tmp1)
      fievre=rbind(fievre,tmp1)
      rm(tmp1)
      }
    }
}
setorder(fievre,deb_sem,sites)
#

#inline historical occurence:
fievre[,vals:=paste(SyndF,collapse = "-"),by="sites"]

#append latest week per site:
fievre[,SyndF:=NULL]
lastweek= unique(mydata[as.Date(deb_sem)==max_deb_sem-7, list(sites,SyndF)],by=NULL)
lastweek[,SyndF:=sum(SyndF),by="sites"]
lastweek=unique(lastweek,by=NULL)

lastweek[,SyndF:=as.character(SyndF)]
lastweek[is.na(SyndF)==T,SyndF:="na"]                           
fievre= merge(unique(fievre[,list(sites,vals)],by=NULL),
              lastweek , by.x="sites", by.y="sites")
#merge with sentinel_latlong to display name
fievre=merge(fievre,sentinel_latlong[,list(sites,name)],
             by.x="sites",by.y="sites")
#                
setnames(fievre,c("name","vals","SyndF"),
                c("Sites","6 semaines précédentes","Semaine dernière"))

#generate tables:
    knitr::kable(fievre[,c("Sites","6 semaines précédentes","Semaine dernière"),with=F],
                caption="Fièvres dans le réseau sentinel")

  knitr::kable(malaria[,c("Sites","6 semaines précédentes","Semaine dernière"),with=F],
              caption="Paludisme dans le réseau sentinelle")
```

```{r,echo=F, fig.show = "hold" ,out.width = '50%', out.extra='',comment='', message=FALSE , warning=FALSE}
setwd("/media/herimanitra/DONNEES/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel")
#merge with sentinel_latlong:
mydata= tdr_malaria(htc=F)
mydata=merge(mydata,sentinel_latlong, by.x="sites",by.y="sites")
                    
generate_plot(htc="dsd",
              mydata=mydata,
              disease1=malaria,
              disease2=fievre,
              disease1.targetvar="malaria_cases",
              disease2.targetvar="SyndF",
              legend.disease1="Paludisme TDR+",
              legend.disease2="Fièvres",
              title.label="Fièvres et Paludisme dans le réseau sentinelle",
              title.ylab="Cas de Fièvres et Paludisme")
```
