---
title: "PFA dans le réseau sentinelle"
author: "Institut Pasteur de Madagascar"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r,echo=F, fig.width=10, out.extra='',comment='', message=FALSE , warning=FALSE}
setwd("/media/herimanitra/DONNEES/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel")
source("./import_data.R");source("./preprocessing.R");require(ggplot2); require(gridExtra);require(Hmisc)
#Retrieve PFA for HTC sites
mydata= preprocessing_disease(include_all_sites=T)[["PFA"]]

#aggregate occurence by week: 100*because rare disease!
mydata[,occurence:=sum(occurence,na.rm = T),by="code"]
mydata$deb_sem=as.Date(mydata$deb_sem)
mydata[,weeks:=week(deb_sem)]
mydata=mydata[as.Date(deb_sem,origin="1970-01-01")>=as.Date("2015-06-01"),]
d=ggplot(unique(mydata[,list(deb_sem,occurence)],by=NULL), aes(x=deb_sem, y=occurence),
         fill=occurence) 
d= d + geom_bar(stat = "identity",fill="blue") 
d= d + ggtitle(label="PFA dans le réseau sentinel")
d= d + xlab("Date") + ylab("Nb. Cas")
debut_annee=as.numeric(unique(mydata[weeks==1,deb_sem]))
d= d + geom_vline(xintercept = debut_annee,linetype=4,colour="orange")
 d= d + scale_x_date(labels = date_format("%m-%Y"))
#set ylim to 10 if <10
mymax=range(as.numeric(mydata$occurence)[is.na(as.numeric(mydata$occurence))==F])
mymax[2]=ifelse(mymax[2]<10,10,mymax[2])
#
       d = d + scale_y_continuous(breaks= seq.int(from=1,to=mymax[2],by=2) ) 
#
print(d)

```

```{r,echo=F,out.extra='',comment='', message=FALSE , warning=FALSE}
setwd("/media/herimanitra/DONNEES/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel")
mydata= preprocessing_disease(include_all_sites=T)[["PFA"]]
semaine=array()
max_deb_sem=max(as.Date(mydata$deb_sem))
semaine[6]= max_deb_sem-2*7 
p=1
for ( k in 2:6 )
{
  semaine[p]=semaine[6]-(k-1)*7
  p=p+1
}
#select last 07 seven weeks for each disease:

#PFA selection for last 6 weeks before current week:
X=mydata[as.Date(deb_sem) %in% semaine,list(deb_sem,sites,occurence)]
# reverse time order (to be follow report spec)
setorder(X,sites,deb_sem)
#transform NA into XX
X$occurence=as.character(X$occurence)
X[,occurence:=ifelse(is.na(occurence)==T,"na",occurence)]
X[,occurence:=ifelse(nchar(occurence)<2,paste0("0",occurence),occurence)]
#inline historical occurence:
X[,vals:=paste(occurence,collapse = "-"),by="sites"]
#append latest week per site:
X[,occurence:=NULL]
lastweek=unique(mydata[as.Date(deb_sem)==max_deb_sem-7,list(sites,occurence)],
                by=NULL)
lastweek[,occurence:=as.character(occurence)]
lastweek[is.na(occurence)==T,occurence:="na"]                             
X= merge(unique(X[,list(sites,vals)],by=NULL),lastweek,by.x="sites", by.y="sites")
              
 #append all 54 sites in sentinel_latlong
  sentinel=fread("data/sentinel_codes.csv");
  setnames(sentinel,c("Centre","Code"),c("name","sites") )
  sentinel[,sites:=tolower(sites)]
  sentinel_latlong=rbind(sentinel_latlong,sentinel[!(sites %in%     sentinel_latlong$sites)],fill=T)
  # format sites's name:
  require(Hmisc);
  sentinel_latlong[,name:=capitalize(tolower(name))]
     
X= merge(X,sentinel_latlong[,list(name,sites)],by.x="sites",by.y="sites")
X[,sites:=NULL]; 
setnames(X,c("name","vals","occurence"),
                 c("Sites","6 semaines précédentes","Semaine dernière"))
#generate tables:
knitr::kable(X[,c("Sites","6 semaines précédentes","Semaine dernière"),with=F],
             caption="PFA dans le réseau sentinel")

```


```{r,echo=F, fig.show = "hold" ,out.width = '50%', out.extra='',comment='', message=FALSE , warning=FALSE}
setwd("/media/herimanitra/DONNEES/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel")
   
    #merge with sentinel_latlong:
    mydata=merge(mydata,sentinel_latlong, by.x="sites",by.y="sites")
    L=length(unique(mydata$name))
    myname = unique(mydata$name)
    for ( p in 1:L )
    {
      X= mydata[name==myname[p],list(code,deb_sem,occurence)]
      X$deb_sem=as.Date(X$deb_sem)
      X[,weeks:=week(deb_sem)]
      setnames(X,"deb_sem","Date")
      d= ggplot(data=X,aes(x=Date,y=occurence)) 
      d=d + geom_bar(stat = "identity",fill='darkblue')
        
       
        
      debut_annee=c(as.numeric(unique(X[weeks==1,Date])))
      d= d + geom_vline(xintercept = debut_annee,
                        linetype=4,colour="orange")
      d=d + ggtitle(label=paste(myname[p]))
      d=d + xlab("Date (ligne verte=1er janvier)") + ylab("Nb. Cas")
      
      
      #set ylim to 10 if <10
mymax=range(as.integer(X$occurence)[is.na(as.integer(X$occurence))==F])
mymax[2]=ifelse(mymax[2]<10,10,mymax[2])
#
       d = d + scale_y_continuous(breaks= seq.int(from=0,to=mymax[2],by=1) ) 
      d= d + scale_x_date(labels = date_format("%m-%Y"))
      print(d)
    }
```