########################Execute report using code ####################
require(rmarkdown);require(lubridate)
setwd("/media/herimanitra/Document/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel/report")
render("ILI_sentinelles.Rmd")
rm(list = ls())
render("Diar_sentinelles.Rmd")
rm(list = ls())
render("Palu_sentinelles.Rmd")
rm(list = ls())
render("palu_autoch_sentinelles.Rmd")
rm(list = ls())
render("PFA_sentinelles.Rmd")
rm(list = ls())
source("miss_sent_report.R")
setwd("/media/herimanitra/Document/IPM_sentinelle/sentinel_hrmntr 291115/Sentinel")
rm(list = ls())
source("generate_report.R")