###########################Forecast UI ######################################
myforecast_ui=fluidRow(box(title="Choose a model for prediction",
                           width=12,
                           selectInput(inputId = "mymodel",
                                       label="Model",
                                       choices = list("SARIMAX"="SARIMAX",
                                                      "GH-Filter"="GHFILTER",
                                                      "Kalman-Filter"="KFilter",
                                                      "Random Forest"="RF")))
                       
                       )
# source("import1.R");require(forecast) 
# head(PaluConf) # select Farafangana et
# PaluConf=PaluConf[,list(code,deb_sem,far,mjr)] #spread data:
# #llin: nb de semaine écoulée depuis la dernière distribution de moustiquaire
# 
# PaluConf=as.data.table(gather(PaluConf,key=sites,value=occurence,-c(code,deb_sem)))
# #inverse time 
# setorder(PaluConf,deb_sem)
# #sum both series: PaluConf[,occurence:=sum(occurence,na.rm = T),by="code"]
# #retrieve unique values:
# 
# PaluConf=unique(PaluConf[,list(code,deb_sem,occurence)]) #plot series:
# ts.plot(PaluConf$occurence) 
# ts.plot(log(PaluConf$occurence+1))
# PaluConf[,log_occurence:=log(PaluConf$occurence+1)]
# PaluConf[,mymonth:=month(as.Date(deb_sem))]
# PaluConf[,myyear:=year(as.Date(deb_sem))]
# 
# PaluConf[,occurence:=sum(occurence,na.rm = T),by="mymonth,myyear"]
# PaluConf=unique(PaluConf[,list(occurence,mymonth)])
# ## extract trend in data: PaluConf[,mytime:=as.numeric(as.Date(deb_sem))]
# detrend_model=lm(log_occurence~mytime,data=PaluConf)
# lines(detrend_model$fitted.values,col="green")
# 
# require(ggplot2) #extract years: PaluConf[,years:=substr(code,1,4)] #remove
# #2008 palu2008=PaluConf[years=="2008"];setkey(palu2008,"years")
# setnames(palu2008,"occurence","occurence2008") #2009
# palu2009=PaluConf[years=="2009"];setkey(palu2009,"years")
# setnames(palu2009,"occurence","occurence2009")
# palu2009=palu2009[code!="2009_53"]
# 
# #2010 palu2010=PaluConf[years=="2010"];setkey(palu2010,"years")
# setnames(palu2010,"occurence","occurence2010")
# palu2010=palu2010[code!="2010_53"]
# 
# #2011 palu2011=PaluConf[years=="2011"];setkey(palu2011,"years")
# setnames(palu2011,"occurence","occurence2011")
# palu2011=palu2011[code!="2011_53"]
# 
# #2012 palu2012=PaluConf[years=="2012"];setkey(palu2012,"years")
# setnames(palu2012,"occurence","occurence2012")
# palu2012=palu2012[code!="2012_53"]
# 
# #2013: palu2013=PaluConf[years=="2013"];setkey(palu2013,"years")
# setnames(palu2013,"occurence","occurence2013")
# palu2013=palu2013[code!="2013_53"]
# 
# #2014 palu2014=PaluConf[years=="2014"];setkey(palu2014,"years")
# setnames(palu2014,"occurence","occurence2014")
# palu2014=palu2014[code!="2014_53"]
# 
# #2015 palu2015=PaluConf[years=="2015"];setkey(palu2015,"years")
# setnames(palu2015,"occurence","occurence2015")
# palu2015=palu2015[code!="2015_53"]
# 
# #############Additive model: yt=St+Tt+Et ############# Multiplicative model:
# yt=St×Tt×Et
# 
# #It seems like a multiplicative seasonnality and trend! X=
# cbind(palu2008,palu2009,palu2010,palu2011,palu2012,
# palu2013,palu2014,palu2015) p=ggplot(X, aes(x=1:52)) p=p+geom_line(aes(y =
# log(occurence2008+1), colour = "2008")) p=p+geom_line(aes(y =
# log(occurence2009+1), colour = "2009")) p=p+geom_line(aes(y =
# log(occurence2010+1), colour = "2010")) p=p+geom_line(aes(y =
# log(occurence2011+1), colour = "2011")) p=p+geom_line(aes(y =
# log(occurence2012+1), colour = "2012")) p=p+geom_line(aes(y =
# log(occurence2013+1), colour = "2013")) p=p+geom_line(aes(y =
# log(occurence2014+1), colour = "2014")) p=p+geom_line(aes(y =
# log(occurence2015+1), colour = "2015"))
# 
# p
# 
# ############Simple exponential smoothing ######## ### future obs =f(past obs
# with weight), older obs will get lesser weight ### ŷ
# T+1|T=αyT+α(1−α)yT−1+α(1−α)2yT−2+⋯,## ### is not efficient when there is trend
# in the data
# 
# ############## Holt Winter Linear trend method ########## ##take into account
# trend in the model: myholtforecast=holt( PaluConf$log_occurence, alpha=0.8,
# beta=0.2,h=10) #myholtforecast$model$state #fitted(myholtforecast)
# #myholtforecast$mean forecast(myholtforecast,15)
# ts.plot(PaluConf$log_occurence); lines(myholtforecast$mean,col="green")
# lines(fitted(myholtforecast),col="blue")

###################Exponential Trend method ############
## there exits growth rate component


####################7.4 Damped trend methods

#The forecasts generated by Holt’s linear method display a constant trend
#(increasing or decreasing) indefinitely into the future. 
# Even more extreme are the forecasts generated by the exponential trend
#method which include exponential growth or decline.



################ Holt-Winters seasonal method ######

############### state space models for exponential smoothing ####


################ AR model: In an autoregression model, 
#we forecast the variable of interest using a linear combination of past values of the variable.

#### MA model; we use past error ###
